Update runtime to gnome 42
flathub/org.bluesabre.MenuLibre pull request #4
Opened 2022-03-30 10:23 UTC by FakeShemp

2022-03-30 10:43 UTC, FakeShemp commented
Image links are broken at https://bluesabre.org

2022-03-30 13:26 UTC, TheEvilSkeleton commented
@FakeShemp thanks! I opened https://github.com/bluesabre/menulibre/pull/97, In the meantime, could you patch the appstream file to make sure everything is working well?

2022-09-10 11:04 UTC, FakeShemp commented
bot, build

2022-09-10 14:17 UTC, TheEvilSkeleton requested changes

2022-09-10 14:17 UTC, TheEvilSkeleton commented on org.bluesabre.MenuLibre.yaml
> +        path: 9097faf0965e83312f9fd6950efa35a754e2fd9d.patch
Can you rename the file to `0001-Fix-appstream.patch`?

2022-09-10 14:30 UTC, TheEvilSkeleton approved these changes
Thanks!

2022-09-10 14:30 UTC, merged